### ISSUE TITLE
MQTT 组件 IAR 上编译报错

### ISSUE THREAD

**Issue by chenyong111** [RT-Thread-packages/paho-mqtt#16]
paho_mqtt.h 文件中：

    enum __attribute__ ((aligned (4))) QoS { QOS0, QOS1, QOS2 };

该语法在 IAR 上不支持编译报错，Keil 上支持，有什么合适的修改方式？

**Comment by armink** [comment]
`enum QoS { QOS0, QOS1, QOS2 } ALIGN(4);`

**Comment by wangyiwu** [comment]
In file included from packages\pahomqtt-latest\MQTTClient-RT\paho_mqtt_pipe.c:13:0:
packages\pahomqtt-latest\MQTTClient-RT\paho_mqtt.h:31:37: error: expected declaration specifiers or '...' before numeric constant
 enum QoS { QOS0, QOS1, QOS2 } ALIGN(4);

我也有同样的错误

**Comment by wangyiwu** [comment]
@armink  your code getting same erorr
