### ISSUE TITLE
MQTT中订阅相关问题

### ISSUE THREAD

**Issue by SunXofRTT** [RT-Thread-packages/paho-mqtt#29]
1.当未订阅topic的情况下，尝试连接MQTT的服务器，在paho_mqtt_pipe.c ->line 832 : const char *topic = c->messageHandlers[i].topicFilter; 中 topic参数为空，后续会导致出错。
2.需要提供专门用于订阅topic的API，当前代码，没提供多次订阅的功能(比如：开始订阅了一个topic，连接上代理后，还想再订阅一个topic。这种操作就无法实现)

**Comment by Lawlieta** [comment]
V1.1.0 版本已经支持动态订阅与取消订阅功能
