### ISSUE TITLE
Client class

### ISSUE THREAD

**Issue by joylees** [RT-Thread-packages/paho-mqtt#37]
I am trying to test the sample file but it is referring to a client class. I cannot find it anywhere in the source. Do I need to create my own client class?

**Comment by Lawlieta** [comment]
Yes, you need to create a client object by yourself, you can refer to the example for the way to create it or you can read [user-guide.md](https://github.com/RT-Thread-packages/paho-mqtt/blob/master/docs/user-guide.md) to find out how the package is used.
