### ISSUE TITLE
能不能支持直接使用IP作为MQTT服务器地址，使用URL还要先进行域名解析

### ISSUE THREAD

**Issue by xiaofyao** [RT-Thread-packages/paho-mqtt#40]
目前只支持URL作为MQTT服务器的地址，而不支持直接用IP地址

如果用URL的话，我看了源码，还要进行域名解析，解析成IP地址。能不能开发一个直接使用IP作为MQTT服务器地址的功能？

**Comment by easyeagel** [comment]
IP地址可以直接用，如: tcp://127.0.0.1:1883，这也是一个合法的URI，可以正常使用。
