### ISSUE TITLE
单包大小>1024左右, 进入到default_callback 中 , mqttclient 反复无限重启

### ISSUE THREAD

**Issue by luzefeng123** [RT-Thread-packages/paho-mqtt#42]
硬件使用w5500 , 软件使用paho -mqtt 最新软件包
数据接收长度小于 1000字节. 可以正常使用, 
但是其他设备发布消息单包长度超过 1024 - 1030 以上后, 会进入default call back 回调函数中, 而且整个mqtt软件模块,接下来就会无限反复重启, 提示ping 超时,
其他网络应用正常使用, 可以正常 使用 finsh 功能ping 路由器, mqtt 服务器 , 开的tcp 也能正常使用,这个有办法解决吗? 或者提高接收缓冲区大小, 没找到在哪里设置

**Comment by Lawlieta** [comment]
调整一下 MQTT 客户端初始化是定义的收发缓冲区数据长度试试，如下图所示

![图片](https://user-images.githubusercontent.com/24888038/83845306-2b532600-a73b-11ea-8d15-ce4dbc0c7d15.png)

**Comment by luzefeng123** [comment]
> 调整一下 MQTT 客户端初始化是定义的收发缓冲区数据长度试试，如下图所示
> 
> ![图片](https://user-images.githubusercontent.com/24888038/83845306-2b532600-a73b-11ea-8d15-ce4dbc0c7d15.png)

问题已经解决 非常感谢
