### ISSUE TITLE
Bug fix: 内存操作错误

### ISSUE THREAD

**Issue by lincoln310** [RT-Thread-packages/paho-mqtt#43]
文件 : paho_mqtt_pipe.c, 939行
应该是    data[msg_len-1] = 0;  //错误的写成了     data[msg_len] = 0;  导致内存操作问题

**Comment by liukangcc** [comment]
![image](https://user-images.githubusercontent.com/44889940/157818542-831f984a-4ece-4b7c-8841-636eb00f470e.png)

没找到 data[msg_len] = 0;
