### ISSUE TITLE
paho_mqtt_publish implement bug

### ISSUE THREAD

**Issue by MilesWangSeven** [RT-Thread-packages/paho-mqtt#45]
int paho_mqtt_publish(MQTTClient *client, enum QoS qos, const char *topic, const char *msg_str);
This API implement is dangerous. No initial value given for dup/id of MQTTMessage.
sometimes id default value is 0 which is relative to stack, when some code change.
It's take me several days to find where the bug is.

**Comment by mysterywolf** [comment]
Thank you https://github.com/RT-Thread-packages/paho-mqtt/pull/48
