### ISSUE TITLE
关于例程paho_mqtt_app中的client，有没有必要定义两个？

### ISSUE THREAD

**Issue by chenyuhui1995** [RT-Thread-packages/paho-mqtt#7]
在跟服务器对接时，服务器的开发人员说应当定义两个client ，一个用于发布，一个用于订阅；
我看了下结构体MQTTClient 里面有用发布、订阅和遗言的主题。一个client就能满足发布订阅。请问有必要创建两个MQTTClient 一个用于发布，一个用于订阅？

**Comment by aozima** [comment]
MQTT本身没有这个要求。
订阅的连接也可以发布消息。

为了简单和方便，可以独立一个用于发布。
两个client_id一般不能相同

**Comment by uke271890** [comment]
谢谢aozima解答！
为什么会产生这个问题的原因：1.是服务器收不到设备掉线。要求让我建立两个client解决这种情况。
为什么服务器收不到设备掉线的信息？
1.我设置心跳包时间太长了，导致了服务器的开发人员认为没有收到MQTT服务器所发的遗言（实际是有的）。
2.MQTT的这种机制就不用我们手动发送心跳包了，要满足这种机制就要设置遗言的主题并且另一端（服务器）要监听这个遗言的主题。
